fodder_crops = ["Maize and products",
                "Wheat and products",
                "Sorghum and products",
                "Barley and products",
                "Soyabeans",
                "Pulses",
                "Rice (Milled Equivalent)",
                "Sugar beet",
                "Oilcrops",
                "Potatoes and products",
                "Cassava and products",
                "Fruits - Excluding Wine"]
